version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - db
    command: "php artisan serve --host=0.0.0.0 --port=8000"
  db:
    container_name: database
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/mysql:/var/lib/mysql
    restart: always
    networks:
      - app-network
networks:
  app-network:
